/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('items').del()
  await knex('items').insert([
    { item_id: '1', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '1'},
    { item_id: '2', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '1'},
    { item_id: '3', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '1'},
    

    { item_id: '4', 
      item_name: "salad", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '2'},
    { item_id: '5', 
      item_name: "salad", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '2'},
    { item_id: '6', 
      item_name: "salad", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '2'},
    

    { item_id: '7', 
      item_name: "dessert", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '3'},
    { item_id: '8', 
      item_name: "dessert", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '3'},
    { item_id: '9', 
      item_name: "dessert", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '3'},
    

    { item_id: '10', 
      item_name: "appie", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '4'},
    { item_id: '11', 
      item_name: "appie", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '4'},
    { item_id: '12', 
      item_name: "appie", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '4'},
    

    { item_id: '13', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '5'},
    { item_id: '14', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '5'},
    { item_id: '15', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '5'},
    

    { item_id: '16', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '6'},
    { item_id: '17', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '6'},
    { item_id: '18', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '6'},
    

    { item_id: '19', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '7'},
    { item_id: '20', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '7'},
    { item_id: '21', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '7'},
    

    { item_id: '22', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '8'},
    { item_id: '23', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '8'},
    { item_id: '24', 
      item_name: "halibut", 
      item_description: "some description here", 
      item_price: "40.75", 
      category_id: '8'},
  ]);
};
